version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    ports:
      - "8083:8083"   # 기본 Kafka Connect REST API 포트
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
    depends_on:
      - kafka

  configure-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/configure-service:1.0
    ports:
      - "8888:8888"

  service-discovery:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/service-discovery:1.0
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=service-discovery
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_METRICS_ENABLE_ALL=false
      - MANAGEMENT_METRICS_BINDERS_SYSTEM_ENABLED=false
      - MANAGEMENT_METRICS_BINDERS_JVM_ENABLED=false
      - MANAGEMENT_METRICS_BINDERS_PROCESSOR_ENABLED=false
      - MANAGEMENT_METRICS_BINDERS_DISKSPACE_ENABLED=false
    ports:
      - "8761:8761"

  apigateway-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/apigateway-service:1.0
    depends_on:
      - service-discovery
      - configure-service
    ports:
      - "8080:8080"

  user-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:1.0
    depends_on:
      - service-discovery
      - configure-service
    ports:
      - "8081:8081"

  schedule-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/schedule-service:1.0
    depends_on:
      - service-discovery
    ports:
      - "8084:8084"

  theater-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/theater-service:1.0
    depends_on:
      - service-discovery
    ports:
      - "8082:8082"

  movie-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/movie-service:1.0
    depends_on:
      - service-discovery
      - redis
    ports:
      - "8086:8086"

  book-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/book-service:1.0
    depends_on:
      - service-discovery
      - kafka
    ports:
      - "8087:8087"

  payment-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/payment-service:1.0
    depends_on:
      - service-discovery
      - kafka
    ports:
      - "8085:8085"

  seat-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/seat-service:1.0
    depends_on:
      - service-discovery
      - kafka
    ports:
      - "8089:8089"


