version: '3.9'

services:

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: brian981103
      MYSQL_DATABASE: movieDB
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.0
    ports:
      - "8083:8083"   # 기본 Kafka Connect REST API 포트
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: 0.0.0.0
    depends_on:
      kafka:
        condition: service_healthy

  configure-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/configure-service:1.0
    ports:
      - "8888:8888"

  service-discovery:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/service-discovery:1.0
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=service-discovery
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_METRICS_ENABLE_ALL=false
      - MANAGEMENT_METRICS_BINDERS_SYSTEM=false
      - MANAGEMENT_METRICS_BINDERS_JVM=false
      - MANAGEMENT_METRICS_BINDERS_PROCESSOR=false
      - MANAGEMENT_METRICS_BINDERS_DISKSPACE=false
    ports:
      - "8761:8761"

  apigateway-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/apigateway-service:1.0
    depends_on:
      - service-discovery
      - configure-service
    ports:
      - "8000:8000"

  user-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/user-service:1.0
    depends_on:
      - service-discovery
      - configure-service
      - apigateway-service
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8081:8081"

  schedule-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/schedule-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8084:8084"


  theater-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/theater-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8082:8082"

  movie-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/movie-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8086:8086"

  book-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/book-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8087:8087"

  payment-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/payment-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8085:8085"

  seat-service:
    image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/seat-service:1.0
    depends_on:
      - service-discovery
      - apigateway-service
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/movieDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: brian981103
    ports:
      - "8089:8089"

volumes:
  db_data:
