server:
  port: 8761

spring:
  application:
    name: service-discovery

  cloud:
    config:
      uri: http://13.124.103.158:8888
      name: movie

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

management:
  metrics:
    enable-all:
      false