server:
  port: 8761

spring:
  application:
    name: service-discovery

  cloud:
    config:
      uri: http://localhost:8888
      name: movie

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false