server:
  port: 8082

spring:
  application:
    name: theater-service

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mariadb://db:3306/movieDB?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: brian981103

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true