server:
  port: 8087

spring:
  application:
    name: book-service

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mariadb://localhost:3306/movieDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: brian981103

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true



eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://15.164.50.252:8761/eureka
    fetch-registry: true
    register-with-eureka: true
