server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka

spring:
  application:
    name: apigateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # user 등록
            - id: user-service-register
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/users
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

            # user 로그인
            - id: user-service-login
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/user-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            # 영화
            - id: movie-service
              uri:
                lb://MOVIE-SERVICE
              predicates:
                - Path=/movie-service/**

            # 상영관 + 좌석
            - id: theater-service
              uri:
                lb://THEATER-SERVICE
              predicates:
                - Path=/theater-service/**
            
            # 상영 등록
            - id: schedule-service
              uri:
                lb://SCHEDULE-SERVICE
              predicates:
                - Path=/schedule-service/**

            # 좌석
            - id: seat-service
              uri:
                lb://SEAT-SERVICE
              predicates:
                - Path=/seat-service/**

            - id: book-service
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/book-service/bookings
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - AuthorizationHeaderFilter

            # 예매
            - id: book-service
              uri:
                lb://BOOK-SERVICE
              predicates:
                - Path=/book-service/**

            # 결제
            - id: payment-service
              uri:
                lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**


